@@include("../../blocks/modules/header/header.js")
@@include("../../blocks/modules/modals/modals.js")
@@include("../../blocks/modules/tabs-block/tabs-block.js")
@@include("../../blocks/modules/home-intro/home-intro.js")
@@include("../../blocks/modules/story-slider/story-slider.js")
@@include("../../blocks/modules/s-news/s-news.js")
@@include("../../blocks/modules/brands-list/brands-list.js")
@@include("../../blocks/modules/s-text/s-text.js")
@@include("../../blocks/modules/catalog-filter/catalog-filter.js")

document.addEventListener('DOMContentLoaded', () => {
    modalsInit()
    headerController()
    homeIntro()
    tabsBlockInit()
    storySlidersInit()
    sNewsSliders()
    brandsList()
    catalogFilter()
    sText()
})